### ISSUE TITLE
some bugs in  charades_dataloader.py, when computing the center of G* Ground truth Heat-map

### ISSUE THREAD

**Issue by wemchao** [dairui01/MS-TCT#1]
on line 51
```python
if fr / fps + 1 > mid_point and fr / fps < mid_point:
```
When extracting features, one segment is used every 8 frames. Usually, the frame rate of the original video is 25 frames, so it is equivalent to 3 segments per second, so at this time fps=3, there are usually three segments that meet the conditions. Therefore, in the subsequent operation counting num_action, there will be a problem of multiple records, and the heat-map will also be inaccurate.

**Comment by dairui01** [comment]
Thanks for your intertest in this work.
It seems that it is a small error in the code. As you pointed it out, it should be `if (fr+1) / fps > mid_point and fr / fps < mid_point` to limit the mid_point to a single segment. I will verify that and update the code soon.
