### ISSUE TITLE
Unmatched shape of input to I3D block

### ISSUE THREAD

**Issue by KhanhNgoDuy** [dairui01/MS-TCT#5]
Hi, I have some question about the i3d repo that you mentioned in the readme section.

As far as I understand, the original repo loads 1 folder of image (which may contains hundreds of images, assuming a total of `t` frames) for each epoch, concatenates them and feed to the i3d model to get 1 feature vector (1 `.npy` file).
But as you said in the MS-TCT paper, you divided the folder into T segments, each contains 8 frames. So the correct way is to seperate `t` frames into `T = t/8` segments, and feed each of these segments into the i3d to get T feature vectors right?

As I followed your paper, each input of i3d should have dimension `b, c, t, h, w = (1, 3, 8, 224, 224)`. But right before the last layer `avg_pool`, this input's dimension becomes `(1, 1024, 1, 7, 7)` while the kernel of `avg_pool` is `(2, 7, 7)` (larger than the input's temporal dimension).

Is my way of thinking correct? If so, how do you adjust the architecture of i3d? Thank you in advance!

This is the dimension of the input after each stage
![image](https://user-images.githubusercontent.com/94754952/200900631-74e3b6c1-cbaf-4e21-8320-27d234460fe5.png)

**Comment by dairui01** [comment]
If you extracted the features for a video with length T using that I3D repo, the output feature should in a dimension around [T/8, 1, 1, 1024]. As in MS-TCT, we assign about 8 frames of annotation into a single feature vector, thus we said that each feature represents 8 frames. You can utilize this I3D repo to extract the feature, the extracted feature can be read directly by our model. Previous methods (e.g., super event, TGM) which rely on these I3D features are following the same step.
