### ISSUE TITLE
Extract feature procedure

### ISSUE THREAD

**Issue by KhanhNgoDuy** [dairui01/MS-TCT#8]
Hello, I'm following your paper to train MS-TCT for another dataset, and I first need to get the extracted features. Did you divide each video into 8-frame segments and use each of those 8 frames as input for the I3D, or did you use a whole video as input? Thank you in advance!

**Comment by dairui01** [comment]
MS-TCT can process on top of any temporal features of different backbones. On Charades we followed the PyTorch-I3D repo that process on the whole video. But you can also use other backbones and extract the feature by small window size. In our recent experiment, we utilize the ViT-based backbone and it works pretty well. 

If you choose to use the same I3D network as we used in Charades, you can check this issue as well for the dimension: 
https://github.com/dairui01/MS-TCT/issues/5#issuecomment-1309818034

**Comment by KhanhNgoDuy** [comment]
Thank you for your fast response. I have another question about the Scale Mixer component.

In this step, the labeling for every frame can be wrong or overlapped since the frame indices (in my annotation file) become floating values instead of integer. 

Then is it recommended to upsample the output of each stage from the Temporal Encoder to the original video's length, so that the annotation will be exact?

**Comment by dairui01** [comment]
Why is the float value a problem for the annotation error in frames? 
If your input is video data and the annotation is in float values of seconds. You can set fps as you want and map the annotation in frames. I don't think it will lead to any issues with Time Scale Mixer.
